Repository streamnative/aop, pull requests merged in 2022-10, with the labels that each got.

#619 Create durable exchange topic cursor for queue
  .github/workflows/pr-qpid-jms-test.yml
  .github/workflows/pr-test.yml
  amqp-client-auth/pom.xml
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AbstractAmqpExchange.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AbstractAmqpQueue.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpExchange.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpQueue.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/impl/PersistentExchange.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/impl/PersistentQueue.java
  pom.xml
  tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/qpid/core/AoPBrokerAdmin.java
  tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/qpid/core/QpidJMSTestException.java
  tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/qpid/jms_1_1/acknowledge/RecoverTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpTestBase.java
Labels: no-need-doc, release/2.10.x

#697 Connection closing optimization
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyConnection.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyHandler.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyService.java
Labels: no-need-doc

#597 bugfix: Default echange consume failed, when broker restart.
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AbstractAmqpExchange.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannel.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpExchange.java
Labels: no-need-doc

#618 Async route exchange messages
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpBrokerService.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpExchangeReplicator.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandler.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpServiceConfiguration.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/ExchangeContainer.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/impl/PersistentExchange.java
  amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpProtocolTestBase.java
  amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/TopicNameTest.java
Labels: no-need-doc, release/2.10.x

#621 Adjust permits for AMQP consumer
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AbstractAmqpMessageRouter.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConsumer.java
Labels: doc-info-missing, release/2.10.x

#620 Optimize direct and fanout exchange route logic
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AbstractAmqpExchange.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/impl/PersistentExchange.java
Labels: no-need-doc, release/2.10.x

#702 Remove @streamnative/platform from CODEOWNERS
  .github/CODEOWNERS
Labels: doc-info-missing
