Repository streamnative/aop, pull requests merged in 2022-07, with the labels that each got.

#590 bugfix: High Memory usage caused memory overflow.
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpBrokerDecoder.java
Labels: doc-info-missing

#595 feat: add token authentication support
  amqp-client-auth/pom.xml
  amqp-client-auth/src/main/java/io/streamnative/rabbitmq/authentication/MechanismException.java
  amqp-client-auth/src/main/java/io/streamnative/rabbitmq/authentication/TokenCredentialsProvider.java
  amqp-client-auth/src/main/java/io/streamnative/rabbitmq/authentication/TokenSaslConfig.java
  amqp-client-auth/src/main/java/io/streamnative/rabbitmq/authentication/package-info.java
  amqp-client-auth/src/test/java/io/streamnative/rabbitmq/authentication/TokenSaslConfigTest.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpBrokerService.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpClientDecoder.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConnection.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyConnection.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyHandler.java
  pom.xml
  tests/pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpTokenAuthenticationTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/authentication/TokenAuthenticationTest.java
Labels: doc-required

#602 feat: add basic authentication support
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConnection.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/authentication/AuthenticationProviderBasic.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/authentication/package-info.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpTokenAuthenticationTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/authentication/PlainAuthenticationTest.java
Labels: doc-required

#608 [fix] release the buf when proxyConnection init
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyHandler.java
Labels: no-need-doc

#598 [fix] After adding entries release the data
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpEntryWriter.java
Labels: no-need-doc

#575 Fix exclusive consume problem
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConsumer.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/PulsarDeduplicationWorkAroundTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/RabbitMQMessagingTest.java
  tests/src/test/resources/log4j2.xml
Labels: no-need-doc

#622 [fix]consume large messages (body size > 10*1024) failed
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConnection.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/RabbitMQMessagingTest.java
Labels: no-need-doc

#627 Remove pulsar-zookeeper-utils dependency
  pom.xml
Labels: doc-info-missing, release/2.10.x, release/2.9.x

#628 Add pulsar bom dependency
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannel.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandler.java
  amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpEncodeHandlerTest.java
  amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpProtocolTestBase.java
  amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpTopicManagerTest.java
  amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/TopicNameTest.java
  amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockManagedLedger.java
  amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockSubscription.java
  pom.xml
Labels: no-need-doc

#630 Add exchange admin endpoints
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannel.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandler.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpServiceConfiguration.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/ExchangeService.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/ExchangeServiceImpl.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/QueueServiceImpl.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/Exchanges.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/Vhosts.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/impl/BaseResources.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/impl/ExchangeBase.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/impl/package-info.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/model/ExchangeBean.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/model/ExchangeDeclareParams.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/model/VhostBean.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/model/package-info.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/package-info.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/common/exception/AoPException.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/utils/ExchangeUtil.java
  tests/src/test/java/com/rabbitmq/client/test/HttpUtil.java
  tests/src/test/java/com/rabbitmq/client/test/JsonUtil.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AdminTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpTestBase.java
Labels: doc-required

#637 Support queues rest api
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AbstractAmqpQueue.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannel.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpQueue.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/QueueService.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/QueueServiceImpl.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/Queues.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/impl/BaseResources.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/impl/ExchangeBase.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/impl/QueueBase.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/model/QueueBean.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/model/QueueDeclareParams.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/utils/ExceptionUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AdminTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/RabbitMQAminDemo.java
Labels: doc-required

#638 Support bindings rest api
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannel.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/QueueService.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/QueueServiceImpl.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/Bindings.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/Queues.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/impl/BaseResources.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/impl/BindingBase.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/model/BindingBean.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/model/BindingParams.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/utils/ExceptionUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AdminTest.java
Labels: doc-required

#639 Support delete queue
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/QueueServiceImpl.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AdminTest.java
Labels: no-need-doc

#493 Support persistent queue delay messages.
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AbstractAmqpMessageRouter.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpQueue.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/IndexMessage.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/impl/InMemoryQueue.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/impl/PersistentQueue.java
  amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/utils/MessageConvertUtils.java
  amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/IndexMessageTest.java
  amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/MessageConvertTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/RabbitMQMessagingTest.java
Labels: no-need-doc
